# Generated by Django 4.2.6 on 2023-10-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='master_plans/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo/')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo_design/')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('unavailable', 'Недоступно'), ('reserved', 'Зарезервировано')], max_length=100)),
                ('count_bedroom', models.IntegerField()),
                ('land_area', models.IntegerField()),
                ('building_area', models.IntegerField()),
                ('villa', models.IntegerField()),
                ('price', models.IntegerField()),
                ('design', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.design')),
            ],
        ),
        migrations.CreateModel(
            name='TypePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='type/')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ManyToManyField(blank=True, to='project.typephoto')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('count_villa', models.IntegerField()),
                ('building_area_from', models.IntegerField()),
                ('building_area_to', models.IntegerField()),
                ('land_area_from', models.IntegerField()),
                ('land_area_to', models.IntegerField()),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('video', models.URLField()),
                ('characteristic', models.ManyToManyField(blank=True, to='project.characteristic')),
                ('count_bedrooms', models.ManyToManyField(blank=True, to='project.bedroom')),
                ('design', models.ManyToManyField(blank=True, null=True, to='project.design')),
                ('master_plan', models.ManyToManyField(blank=True, to='project.masterplan')),
                ('photo', models.ManyToManyField(blank=True, to='project.photo')),
                ('price_list', models.ManyToManyField(blank=True, null=True, to='project.pricelist')),
            ],
        ),
        migrations.AddField(
            model_name='pricelist',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.type'),
        ),
        migrations.AddField(
            model_name='design',
            name='photo',
            field=models.ManyToManyField(blank=True, to='project.photodesign'),
        ),
    ]
