# Generated by Django 4.2.6 on 2023-10-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_design_remove_project_price_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
