# Generated by Django 4.2.3 on 2023-10-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_description2_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='count_bedrooms',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='description2',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
