# Generated by Django 4.2.6 on 2023-10-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_pricelist_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='count_bedrooms',
        ),
        migrations.DeleteModel(
            name='Bedroom',
        ),
        migrations.AddField(
            model_name='project',
            name='count_bedrooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
