# Generated by Django 4.2.6 on 2023-10-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
    ]
